# Generated by Django 5.0 on 2024-08-10 20:21

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_tasklistmodel_taskmodel_attachmentmodel_delete_task"),
        ("user", "0003_alter_profilemodel_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmentmodel",
            options={"verbose_name": "Attachment"},
        ),
        migrations.AlterModelOptions(
            name="tasklistmodel",
            options={"verbose_name": "Task List"},
        ),
        migrations.AlterModelOptions(
            name="taskmodel",
            options={"verbose_name": "Task"},
        ),
        migrations.AddField(
            model_name="attachmentmodel",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profilemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attachmentmodel",
            name="data",
            field=models.FileField(upload_to=task.models.GenerateTaskImagePath()),
        ),
    ]
