# Generated by Django 5.0 on 2024-05-23 10:48

import django.db.models.deletion
import house.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('image', models.FileField(blank=True, null=True, upload_to=house.models.GenerateHouseImagePath())),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True, null=True)),
                ('desc', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('not_completed_tasks_count', models.IntegerField(default=0)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_manager', to='user.profilemodel')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
